// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1614777653);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1614777773);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1614777683);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210203182138");
user_pref("extensions.lastAppVersion", "78.7.1");
user_pref("extensions.lastPlatformVersion", "78.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"2b25f569-227c-4456-a0b4-5779674cc660\",\"default-theme@mozilla.org\":\"db1539ab-9a56-4112-aea1-07e069abce8f\"}");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "a3677f5a-71d6-4e0a-a42c-48f91aaa8e0");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("security.sandbox.plugin.tempDirSuffix", "abae0cfc-2d00-4fd2-9526-f46818dd3df6");
user_pref("toolkit.telemetry.cachedClientID", "4d9796c2-ad4c-4a20-a43c-1729e2a3ca91");
user_pref("toolkit.telemetry.previousBuildID", "20210203182138");
