// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1614688200);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1614779909);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1614688198);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{9d6b0320-f0be-4904-a82e-c4f73fda2ef9}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210222142601");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1614688200");
user_pref("browser.slowStartup.averageTime", 2257);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20210222142601");
user_pref("browser.startup.homepage_override.mstone", "86.0");
user_pref("browser.startup.lastColdStartupCheck", 1614779902);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 4);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1614688200101");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "86.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210222142601");
user_pref("extensions.lastAppVersion", "86.0");
user_pref("extensions.lastPlatformVersion", "86.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"79115b91-5656-401d-9cdf-dc8697d67f84\",\"formautofill@mozilla.org\":\"8da98220-98f6-40ee-a723-b0d37664de77\",\"screenshots@mozilla.org\":\"ce0cfb31-a5e6-45bd-8142-1d22781f3901\",\"webcompat-reporter@mozilla.org\":\"91a5ec70-5bb7-4a65-b55f-adcdb4672fdb\",\"webcompat@mozilla.org\":\"e13ea295-7d78-4ba0-8158-3952532a2f9d\",\"default-theme@mozilla.org\":\"fb9dca93-d82e-417a-81ee-eccb2900b5e3\",\"google@search.mozilla.org\":\"b9b239a1-a8e0-4f95-a5ec-dad5c9cc79e7\",\"amazondotcom@search.mozilla.org\":\"06b9f1a8-5287-48ac-9910-04e7c7020c6e\",\"wikipedia@search.mozilla.org\":\"8bd40ac0-51bd-4a16-881a-b87aec2b500b\",\"bing@search.mozilla.org\":\"cae0b330-e98d-4cb3-9b3a-592c79e19c8d\",\"ddg@search.mozilla.org\":\"591b0279-6f9c-46a4-b8e8-6144321a53d8\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1614688200);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "580849fe-d24e-41d3-84c1-f71ac8c78537");
user_pref("security.sandbox.plugin.tempDirSuffix", "5d1a5565-2c21-4ac3-885b-4facaa1221db");
user_pref("toolkit.startup.last_success", 1614779900);
user_pref("toolkit.telemetry.cachedClientID", "2a36e2fa-5907-4d5f-a7a2-c95da5e357b5");
user_pref("toolkit.telemetry.previousBuildID", "20210222142601");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
